name: Generate Commit Grid Images

on:
  schedule: # Runs at 12am UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Commit Grid Images
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-commit-grid-light.svg?palette=github
            dist/github-commit-grid-dark.svg?palette=github-dark

      - name: Upload Commit Grid Images
        uses: actions/upload-artifact@v3
        with:
          name: commit-grid-images
          path: |
            dist/github-commit-grid-light.svg
            dist/github-commit-grid-dark.svg

      - name: Commit and Push Commit Grid Images
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Updated commit grid images'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
